version: "3.7"
services: 
  backend_pos:
    image: "aldifarzum/dockerpos-backend:v1.0.0.2"
    restart: always    
    volumes:
      - ./backend/logfile:/backend/logfile
    deploy:
      mode: replicated
      replicas: 3
      resources:
        limits:
          cpus: '1'
          memory: 50M
    networks:
      - netnetwork 
    environment:
        PGUSER: admin
        PGHOST: 54.237.63.193
        PGDATABASE: postgres
        PASSWORD: secret
        PGPORT: 5400
        SERVICEPORT: 4500
        REDIS_PORT: 6379
        REDIS_PASSWORD: aldi1234
        REDIS_HOST: 54.237.63.193
  frontend_pos:    
    image: "aldifarzum/dockerpos-frontend:v1.0.0.1"
    ports:
      - 80:80
      - 443:443
    networks:
      - netnetwork
    depends_on:
      - backend_pos
    environment:
     -  VUE_APP_URL=http://54.237.27.238:9191/backend/
     -  VUE_APP_STATIC_URL=http://54.237.27.238:9191/backend/
    volumes: 
      - ./frontend:/dist/public
      - ./conf.d:/etc/nginx/conf.d
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
  certbot:
  image: certbot/certbot:latest
  command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email accessrate23905@gmail.com --agree-tos --no-eff-email -d tester.rivaldiweb.xyz
  volumes: 
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
  
networks:
  netnetwork:
      
volumes:
  pgdata:
  pgadmin-data:
